# Generated by Django 3.1.5 on 2021-02-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='snippet',
            field=models.TextField(default=models.TextField(), max_length=50),
        ),
    ]
