# Generated by Django 3.1.5 on 2021-02-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='snippet',
        ),
    ]
