# Generated by Django 3.1.5 on 2021-02-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
